### ISSUE TITLE
add plotting to dataset page

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#101]
right now plotting is only available on the bin page.

**Comment by mike-kaimika** [comment]
Making note that we should hold on this until we combine both pages into one like we discussed on the last call, since then this one gets taken care of automatically

**Comment by mike-kaimika** [comment]
Related to #104

**Comment by mike-kaimika** [comment]
This is a moot item now that we have a combined bin/dataset page
