### ISSUE TITLE
hide timeline in bin mode and provide link(s) to dataset(s) the bin is in

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#109]
the dataset links should go to the dataset view with that bin selected

**Comment by joefutrelle** [comment]
also don't show the next / previous buttons in bin mode unless someone has navigated from the bin selected in the dataset or provided a dataset ID in the incoming URL..

I'm thinking we need URLs like

`/bin?id=D20171231T123456_IFCB010&dataset=mvco`

where the dataset parameter is optional, and

`/timeline?{params}`

where params could be dataset id, selected bin id, tags, etc.

**Comment by mike-kaimika** [comment]
This one is complete except for the side conversation about the route (timeline vs bin)
