### ISSUE TITLE
directory management should show product version

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#132]
product version is important for blobs/features (and eventually class score) files.

The defaults when adding a directory should be:
* blobs: 2
* features: 2

**Comment by mike-kaimika** [comment]
There's a directory type of "raw"; is there a default version for that? And I'm assuming that version is just the default, and the user can  change it when adding/modifying a data directory? (unlike on instruments, where its calculated automatically)

**Comment by joefutrelle** [comment]
the version field does not apply to raw data, where the version is determined automatically on a bin-by-bin basis.
