### ISSUE TITLE
set reasonable default axis limits on ROI x/y plot

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#133]
xlim should be 0-1400
ylim should be 0-1050

this is the size of IFCB's camera field.

**Comment by mike-kaimika** [comment]
@joefutrelle When you say "limit" do you mean the x/y axis should be fixed to those values, or that we should strip out data (which would be "bad" data) outside of those bounds?

**Comment by joefutrelle** [comment]
we should fix to those limits, no need to strip out any data

**Comment by joefutrelle** [comment]
^ that commit reference above incorrectly referenced this issue. it was for a different issue.
