### ISSUE TITLE
better visual indication of selected bin rather than highlighting bar in red

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#135]
a vertical line would be good. here's the current site's look:

![image](https://user-images.githubusercontent.com/2365298/62576234-7de95a80-b86a-11e9-975a-e360167cc334.png)

**Comment by mike-kaimika** [comment]
Making note of a Plotly GitHub issue for adding the line. It's quite long; not sure yet if it was solved in a way that meets what we're looking for here:
https://github.com/plotly/plotly.js/issues/2155
