### ISSUE TITLE
set reasonable default y-axis scaling on specific metrics

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#136]
for example the default range for ml_analyzed should be 0-5.

I'll track down what the others should be.

**Comment by joefutrelle** [comment]
@ecrockford suggests horizontal gridlines every ml for concentration (ml_analyzed)

**Comment by sbeaulieu** [comment]
I think it would be helpful to provide the same vertical scale for trigger and image count plots
