### ISSUE TITLE
make back button work in timeline mode

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#138]
1. Click on the timeline to select a bin
1. Click on the timeline somewhere else to select another bin
1. Hit back

You should go back to the bin you selected previously, in timeline mode.

**Comment by mike-kaimika** [comment]
@joefutrelle Can you check this again? It's working for me...might have been fixed with the routing changes that were just merged

**Comment by joefutrelle** [comment]
it works now.
