### ISSUE TITLE
Attribution and funding support information per-dataset

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#174]
Right now the footer is static and indicates a mix of funding sources and attributions that are relevant mostly to the old dashboard.

The new use of the dashboard is that it contains multiple datasets and each one has a different mix of attribution and funding sources.

We should support adding and displaying this type of metadata per-dataset.

**Comment by mike-kaimika** [comment]
@MattCharron32 I think the details of this one were discussed via email. Can you add those comments here?

**Comment by joefutrelle** [comment]
So I'm planning on not doing this in the footer, but showing it across from where the DOI is shown, which is right below the timeline.
