### ISSUE TITLE
switching metric while zoomed in changes resolution

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#176]
1. Zoom in to bin level
1. Change metric

Resolution will change.

This may be related to #85 or #142

**Comment by joefutrelle** [comment]
Looks like when you switch metrics the metrics AJAX call does not send start and end dates--it should be sending the current start and end dates. The effect of this is that it fetches the entire timeline's data at auto resolution.

**Comment by joefutrelle** [comment]
The culprit is `createTimeSeries` which does not add start and end parameters to the AJAX call.

**Comment by mike-kaimika** [comment]
@joefutrelle I pushed an update for this and I think its working, but can you double check the data?
