### ISSUE TITLE
add image share button on combined page

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#178]

**Comment by mike-kaimika** [comment]
![image](https://user-images.githubusercontent.com/24275288/65457656-51a29100-de4c-11e9-9b73-3e12f489e7d9.png)
Does to the left of the grey "X" button work? Or are you thinking of a different location?

**Comment by joefutrelle** [comment]
Works for me.

**Comment by mike-kaimika** [comment]
@joefutrelle For the link, should be a direct link to the image, or to the current, combined page with that image selected already? The latter might take more work to keep the current state of the page in place through the url

**Comment by joefutrelle** [comment]
Make a link to the image page

**Comment by mike-kaimika** [comment]
@joefutrelle Looks like you merged the code for this one into master already, right? Safe to close?

**Comment by joefutrelle** [comment]
Yes
