### ISSUE TITLE
add ability to see and modify skip flag on sets of bins

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#179]

**Comment by mike-kaimika** [comment]
@joefutrelle How do you envision this looking? A separate page that users can get to to see the list of skipped bin? What criteria would a user use (or how would they go about selecting) the bins, in a group, to mark as skipped?

**Comment by joefutrelle** [comment]
Good question. Here are some typical use cases I think we should support

1. An instrument produces bad bins for a while and a user wants to skip a whole time range (typically for a specific dataset/instrument/tags), with possible exceptions for specific bins
1. A user has mistakenly skipped some bins and wants to unskip a bunch of them

Usually there is a small time range for bins that the user wants to skip.

In the current interface we require that the user select a day and then work on skipping and unskipping for that day. Not very satisfactory.

![image](https://user-images.githubusercontent.com/2365298/65264992-db193280-dadd-11e9-9510-0b3ec30e9165.png)

**Comment by joefutrelle** [comment]
Since we can already filter the timeline and zoom in, we could just add controls to skip all visible bins or unskip all bins matching the filters in the visible zoomed-in region. With a reasonable prompt so the user can confirm, which would say something like "Are you sure you want to skip [or unskip] 482 bins?"

This doesn't handle making specific exceptions to skipping a bunch of bins, I think that would require something more like a list view.

Maybe the right solution would be to show all bins in the currently-zoomed-in time range matching the filters as a list where the user could check and uncheck them, including check and uncheck all. This would be a separate page but you'd navigate to it based on the zoomed region and filters.

**Comment by mike-kaimika** [comment]
What if we create a new page to search through bins. Let the user enter start/end dates and whether to show skipped bins. We then provide a result grid (somewhat similar to the one above) with links to the bin page for each bin. Also in the grid would be a checkbox and a "check all" option, along with a button to mark selected bins as skipped?

**Comment by mike-kaimika** [comment]
To handle your last post, we could add a button somewhere on the combined page with "View as list" which would get the user to the search page with the same criteria (which might mean adding some to the criteria I originally suggested). From there they can checkoff as needed and mark as skipped

**Comment by joefutrelle** [comment]
Let's go with that last option you described.

Note that you'll want to set `filter_skip=False` on `bin_query` when determining which bins to show.

**Comment by mike-kaimika** [comment]
First draft of this has been committed. Open questions:
1) When coming from the timeline view to list, we do track tags, instrument and dataset. Do we also need to track the time range visible on the timeline? E.g, to let the user focus the bins down to a smaller list of a day, for instance so they can just update/view those
2) If you select bins, then switch the filter, should those selected bins still remain? Or should it reset each time you switch filters?
3) Do we need a check/uncheck all option?

Now that I'm re-reading this issue thread I can see #1 is almost certainly required, but let me know if that's not the case

**Comment by joefutrelle** [comment]
For question 2, the selection should clear if you switch filters.

**Comment by mike-kaimika** [comment]
@joefutrelle  I pushed an update to allow filtering on the list page. Was that the last item on this issue?
