### ISSUE TITLE
Browser is not caching mosaic page images on the dataset page

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#18]
I haven't investigated fully but it seems like the backend is having to redraw a mosaic page that the user has already seen, when they're on the dataset page.

In contrast, if you navigate to a page you've already seen on the bin page, it displays immediately with no loading indicator. That's the desired behavior.

**Comment by mike-kaimika** [comment]
@joefutrelle Can you try now? I changed around how some of the ajax calls are made; paging between cached data should be quicker now
