### ISSUE TITLE
at certain browser widths, the plot is partially hidden behind the plot images card

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#219]
This hides the plot controls and the only workaround is to increase the width of the browser.

![image](https://user-images.githubusercontent.com/2365298/65982186-bcedf380-e448-11e9-8ccb-2393d370fbcb.png)

**Comment by MattCharron32** [comment]
@joefutrelle  - Can you try changing the width of your browser, even just by the smallest amount - making it wider or more narrow, and see if that corrects the issue?  It does for me, and that would point me towards the appropriate solution.

**Comment by joefutrelle** [comment]
Yes, that works for me

**Comment by MattCharron32** [comment]
@mike-kaimika - Plotly needs a "re-flow" to be triggered when you switch to the plot tab. That should resolve this.

**Comment by mike-kaimika** [comment]
FYI, just making note that I'm still trying to get this to work properly. I can somewhat get the plot not to overlap, but Plotly is adding a ton of padding (especially to the top where its most notable) and I'm not seeing any indication as to why yet

**Comment by joefutrelle** [comment]
in the side by side map implementation this problem now affects the mosaic image and the map.
