### ISSUE TITLE
Hook up blob/outline images

### ISSUE THREAD

**Issue by mike-kaimika** [WHOIGit/ifcbdb#23]

**Comment by joefutrelle** [comment]
Will need to deal with bins that do not have blobs (which will often be the case), I can add code to the Bin model that returns whether or not a bin has blobs.

**Comment by joefutrelle** [comment]
Added `has_blobs` method on Bin

**Comment by joefutrelle** [comment]
This applies to the modals as well as to the image page.

**Comment by mike-kaimika** [comment]
This one is all set
