### ISSUE TITLE
UI for navigating to a specific bin

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#237]
This could be a button with a modal where the user can paste a pid, and it would take the user to the bin view.

Right now Heidi is doing it by editing the URL in the browser address bar, not how we want to do things ...

**Comment by mike-kaimika** [comment]
@joefutrelle I just want to confirm what we talked about the other day for this. The current plan is to add the bin search UI that I had sent a screenshot of to EVERY page, and it would just redirect the user to the bin page for that PID, assuming it exists

I can also allow it to, on the timeline page only, select that bin w/o redirecting as if the user clicked on it. However, the one scenario we'd then have to handle is what to do if the bin is not within what's viewable on the timeline. We can either:
1) Redirect the user to the bin page as if they weren't on the timeline
2) Throw an error and tell the user the bin doesn't exist on the timeline
3) Throw an error but give the user the option of going to the bin page for that pid instead. E.g, "The submitted bin is not within the viewable timeline range. Would you like to view that bin directly instead?" (or something to that effect)

**Comment by joefutrelle** [comment]
Let's keep it simple and just have it go to the bin page.

**Comment by mike-kaimika** [comment]
@joefutrelle I pushed the update where it just goes straight to the bin page. Let me know if anything more is needed
