### ISSUE TITLE
next/previous bin does not behave as expected in case of multiple bins with the same date/time

### ISSUE THREAD

**Issue by hsosik** [WHOIGit/ifcbdb#257]
For discrete samples, we often have replicates: 2-3 bins from the same cast/niskin. These have the same date/time metadata. The next/previous bin buttons should operate with a two level sort: sort first by date/time and second by bin PID.

**Comment by joefutrelle** [comment]
Marking this as a bug because it's already implemented but doesn't work.

**Comment by hsosik** [comment]
By the way, here are some bins that could be used to test the functionality:

Filename | datetime | cast | niskin | cruise
-- | -- | -- | -- | --
D20190820T194720_IFCB115 | 2019-08-20 19:17:59+00:00 | 1 | 17 | EN644
D20190820T201029_IFCB115 | 2019-08-20 19:17:59+00:00 | 1 | 17 | EN644
D20190820T203338_IFCB115 | 2019-08-20 19:17:59+00:00 | 1 | 17 | EN644
D20190820T210404_IFCB115 | 2019-08-20 19:10:41+00:00 | 1 | 2 | EN644
D20190820T212713_IFCB115 | 2019-08-20 19:10:41+00:00 | 1 | 2 | EN644

**Comment by joefutrelle** [comment]
reopening this issue because I've seen incorrect behavior in my testing environment.

**Comment by joefutrelle** [comment]
This still does not seem to work.

**Comment by joefutrelle** [comment]
I believe it's working now.
