### ISSUE TITLE
Map auto-zooms, should preserve zoom level instead

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#260]
When using the map, selecting a bin will zoom way in on the map--too far in. The best behavior would be to preserve the user's previous zoom level.

This happens when the selected bin's marker is clustered, not sure if it happens in other situations.

**Comment by mike-kaimika** [comment]
@joefutrelle 
I pushed an update for this. There's an option for the Leaflet plugin called zoomToBoundsOnClick which does what we want. It did require some additional code to force a "spiderfy" when clicking; it was only doing so originally if the click caused a zoom. Between both changes, I believe this should do what you're looking for

**Comment by mike-kaimika** [comment]
@joefutrelle Anything more needed on this one as well? It seems like the last update to maps took care of most of these map related loose ends

**Comment by joefutrelle** [comment]
I believe this is OK now
