### ISSUE TITLE
admin users need to be able to delete or modify comments added during upload of metadata file

### ISSUE THREAD

**Issue by hsosik** [WHOIGit/ifcbdb#275]
It appears that comments uploaded as part of a metadata csv file appear with no owner and thus no one can delete or edit them. Could / should this be enabled for any user with admin status?

**Comment by joefutrelle** [comment]
That's one possible solution. The other is to set the owner when uploading. I prefer the first solution because the person who wrote the comment is not necessarily the person doing the upload.

**Comment by hsosik** [comment]
And the person fixing the mistake may not be either the person who wrote the comment nor the person who uploaded! Let's do the general admin case--these are comments that are usually collectively assembled from cruise logs, etc. so it's not that easy to assign an owner for that matter.

**Comment by joefutrelle** [comment]
For my reference, the parts of the code that enforce the same-user restriction start [here](https://github.com/WHOIGit/ifcbdb/blob/fe9f04546e756e8d506f3968d29a0e35f90f39ae/ifcbdb/secure/views.py#L200).

**Comment by joefutrelle** [comment]
This fix is complete and deployed, you will need to shift-reload the page. Give it a try.
