### ISSUE TITLE
users want to export tags

### ISSUE THREAD

**Issue by hsosik** [WHOIGit/ifcbdb#279]
I realize tags are stored differently, but would it be practical to add them to the result that's returned from the export metadata api?

**Comment by joefutrelle** [comment]
Sure, the only potential issue I can think of is that for bins with multiple tags, the order in which the tags will appear in the "tag1, tag2, ... tagN" columns won't be guaranteed to be in the same order as they were in the CSV from which they were imported.

**Comment by joefutrelle** [comment]
This is done, but it appears to have a bug in it which I was unable to catch during testing. I'll open that bug and link it here.

**Comment by joefutrelle** [comment]
#284
