### ISSUE TITLE
Mosaic coordinates pre-caching not aware of changes to mosaic size

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#32]
On the dataset page, change the mosaic size and then navigate to an adjacent bin. The mosaic coordinates for its adjacent bin will precache but not in the mosaic size you changed to.

**Comment by mike-kaimika** [comment]
This is fixed; support for passing the view size and scale to the preload coordinates call was already there, but the values being passed to it were bad. The js selector was incorrect causing view size and scale to always be "undefined" when getting passed to the ajax request (and I think urls containing undefined might have been a separate issue at one point, so this fixes that as well)
