### ISSUE TITLE
Triggers: wrong number displayed for each bin

### ISSUE THREAD

**Issue by hsosik** [WHOIGit/ifcbdb#337]
The number of triggers for each bin has not been determined correctly. The number displayed in the Basic Info box is the number of rows in the adc file. The number of triggers is the integer that appears in the last row, first column of the adc file. Those two values only match if there are no camera fields with more than one saved ROI--a fairly rare occurrence in the field data, so lots of bad info is currently displayed in Triggers and Triggers / s and the Trigger Count option on the time series plot.

**Comment by joefutrelle** [comment]
TODO check if this is a bug in pyifcb or in ifcbdb

**Comment by joefutrelle** [comment]
Here's a method in pyifcb that computes trigger rate incorrectly, that will need to be fixed

https://github.com/joefutrelle/pyifcb/blob/9a4a934212fc2e481f8927cf2786436bab647d3e/ifcb/data/bins.py#L96

**Comment by joefutrelle** [comment]
And here's the line from the accession code that computes the number of triggers incorrectly

https://github.com/WHOIGit/ifcbdb/blob/801a0c2c5dc4772d525e9119c7fbd7f4b7fceac1/ifcbdb/dashboard/accession.py#L219

**Comment by joefutrelle** [comment]
Here's the `pyifcb` issue

https://github.com/joefutrelle/pyifcb/issues/66
