### ISSUE TITLE
Get lat/lon/depth metadata from hdr files

### ISSUE THREAD

**Issue by mbrosnahan** [WHOIGit/ifcbdb#355]
We’ve started using our PhytO-ARM code to write lat/lon/depth info to hdr at initial filewrite by IFCBacq. An example hdr is here: https://habon-ifcb.whoi.edu/mdibl/D20220617T184050_IFCB152.hdr

Please consider updating ifcbdb so that it assigns lat/lon/depth by priority:
1. Metadata upload
2. Hdr fields
3. Default time-series location assignment

I’m hoping coding of this relatively trivial. 

Some background info: The PhytO-ARM code is availabe at https://github.com/WHOIGit/PhytO-ARM.git. It can run as a container on Linux variant IFCBs. McLane has added a function to query a PhytO-ARM url for lat/lon/depth info when writing hdr files. With update to ifcbdb we can start updating lat/lon data on e.g. cruise tracks automatically and displaying reports about specific taxa through HAB hub (https://github.com/WHOIGit/whoi-hab-hub.git).

**Comment by joefutrelle** [comment]
In pull request #357
