### ISSUE TITLE
autocomplete tag entry in UI

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#368]
Add autocompletion to the tag entry UI to allow users who are adding tags to begin typing a tag name, and then optionally select a completion.

suggested by @ecrockford

**Comment by ecrockford** [comment]
I think this issue basically already existed https://github.com/WHOIGit/ifcbdb/issues/339  but this current issue #368 might be more clear in it's wording?

**Comment by joefutrelle** [comment]
Good catch, close #339 as duplicate

**Comment by mike-kaimika** [comment]
I've attached a PR for this. Here's what the UI is looking like:
![image](https://user-images.githubusercontent.com/24275288/232347672-b674842f-76fe-4454-be68-b6939c4f768e.png)

The PR works as is, but there is one potential change we may or may not need to make. How, if at all, does the tag list the user is picking from need to be filtered? Right now, its pulling the entire tag list from the backing database table. However, do we need to restrict this to tags within the same dataset or instrument? The backend call to get the list is running Tag.list, which already has filters for those available, so adding them is trivial. Or we can leave it open and show all tags - the only potential concern there is if there are a ton of tags in the database

**Updated Files**
https://github.com/WHOIGit/ifcbdb/pull/370

**Comment by joefutrelle** [comment]
IMO the best option is to search all tags--the idea being to prevent misspelling/variants/fragmentation of the tag metadata (even across datasets and filtering criteria)

I'll let @ecrockford weigh in as well.
