### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by PMassicotte** [WHOIGit/ifcbdb#372]
Hi there.

Do you have any documentation explaining how to install and run the dashboard? We have tried to follow these instructions: https://gist.github.com/joefutrelle/93a4a3b7627dec5276e3e09ef825e116 without success.

Here is the error we are getting:

```bash
running egg_info
creating pyifcb.egg-info
writing pyifcb.egg-info/PKG-INFO
writing dependency_links to pyifcb.egg-info/dependency_links.txt
writing requirements to pyifcb.egg-info/requires.txt
writing top-level names to pyifcb.egg-info/top_level.txt
writing manifest file 'pyifcb.egg-info/SOURCES.txt'
reading manifest file 'pyifcb.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pyifcb.egg-info/SOURCES.txt'
running build_ext
Creating /opt/conda/lib/python3.9/site-packages/pyifcb.egg-link (link to .)
Adding pyifcb 0.0.1 to easy-install.pth file

Installed /pyifcb
Processing dependencies for pyifcb==0.0.1
error: scipy 1.10.1 is installed but scipy<1.9.2,>=1.8; python_version <= "3.9" is required by {'scikit-image'}
```

We also wonder how the data should be organized. Once the dashboard is up and running, should we organize the data in a specific way?

Any help would be appreciated.

**Comment by joefutrelle** [comment]
There are known issues with the build that we are working through this week. The resulting installation process will be simpler and will come with instructions.

**Comment by joefutrelle** [comment]
Installation instructions now up to date.
