### ISSUE TITLE
Bin navigation buttons not working 

### ISSUE THREAD

**Issue by sbatchelder** [WHOIGit/ifcbdb#375]
On behalf of: Noémie Ferdinand <noemieferdinand7@outlook.fr>

I am contacting you because the IFCB MVCO Dashboard website seems to misfunction.

Indeed, I can’t anymore click on the « next bin » and « previous bin », the images are not charging and I can’t select the data from the Dashboard.

Do you know if the website is under maintenance ?

**Comment by joefutrelle** [comment]
This is an operational issue and not an issue with the application code
