### ISSUE TITLE
Dismiss menus by cilcking anywhere

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#389]
When you click any of the top buttons on the webpage (such as dataset or filter) you have to click that button specifically again to make it go away. You can't just click anywhere on the page.

**Comment by mike-kaimika** [comment]
https://github.com/WHOIGit/ifcbdb/pull/391

**Comment by mike-kaimika** [comment]
I realized after I committed the code that its technically possible to have two popovers up at once (datasets and filters) and clicking between them will keep both open. Let me know if we should add additional logic to pinpoint the specific popover you're clicking around on. I think those two being open would be the only time that could occur.
