### ISSUE TITLE
incorrect 'none' tag when upload metadata

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/ifcbdb#390]
The tag "none" is frequently applied. Possibly due to tag column being completely empty? Unclear. Do not want the none tag

**Comment by joefutrelle** [comment]
Yes, this looks like missing values (represented by None in Python) are getting erroneously turned into string and applied as a tag.

**Comment by mike-kaimika** [comment]
This should be all set with the attached PR

**Updated Files**
https://github.com/WHOIGit/ifcbdb/pull/401
