### ISSUE TITLE
Scraping mosaic-generating endpoints results in DOS

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#393]
Endpoints that asynchronously schedule mosaic jobs, when accessed in rapid succession, consume all available CPU and RAM even on reasonably-provisioned machines. These endpoints (will enumerate below) need to be patched so that they don't create these mosaic jobs, which will potentially place mosaic generation at a different point in the rendering process.

**Comment by mike-kaimika** [comment]
This PR will:

- Change the /api/bin API calls to POSTs within the UI
- Prevent the "preload" flag from working unless it was a POST request

**Updated Files**
https://github.com/WHOIGit/ifcbdb/pull/394
