### ISSUE TITLE
read gpsLatitude and gpsLongitude from .hdr during accession

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#396]
Add "gptLatitude" and "gpsLongitude" to the set of synonyms for "latitude" and "longitude" in the metadata import during accession.

**Comment by mike-kaimika** [comment]
@joefutrelle I wasn't sure whether there were two tasks here, or one. The title suggested those fields will appear in the .hdr file, however, I only have the Armstrong dataset on my local and I did not see those in the .hdr file. Is this accurate, if so, can you send over a different dataset that has this use case in play?

I read the first comment as needing to handle these two fields as column names when importing from a .csv file. I've attached a pull request that adds the mapping for the CSV import

Let me know on the first part, and I can update the PR to include the .hdr header adjustments if needed

**Updated Files**
https://github.com/WHOIGit/ifcbdb/pull/398

**Comment by joefutrelle** [comment]
Some newer .hdr files include `gpsLatitude` and `gpsLongitude` so this is a trivial fix of adding those as synonyms for `latitude` and `longitude` when adding a bin during sync. Apologies for the confusion

**Comment by mike-kaimika** [comment]
@joefutrelle I've updated the PR to handle the mapping within the header files
