### ISSUE TITLE
Configurable start position for map

### ISSUE THREAD

**Issue by jonatanmindroad** [WHOIGit/ifcbdb#417]
As mentioned in TODO comment in /ifcbdb/assets/js/site.js

It would be nice to be able to set default start location for the map in django settings file.

**Comment by mike-kaimika** [comment]
A PR is ready for this one. I allows the default latitude, longitude and zoom level to be configured via a new admin page. It also cleans up so unrelated items that were found while tackling this one

![image](https://github.com/user-attachments/assets/b68c4959-a8a4-41f0-8895-dd5cc2e02d66)


**Updated Files**
https://github.com/WHOIGit/ifcbdb/pull/421

**Comment by jonatanmindroad** [comment]
Very nice with this admin page!

It did not work for me however. I entered a location in Sweden but I still see the North American east coast on the dashboard. Or have I perhaps misunderstood what is supposed to happen? Is there perhaps a cached position?

**Comment by mike-kaimika** [comment]
@jonatanmindroad Can you post a screenshot of app settings page, and provide the latitude/longitude values that you're using? Additionally, try to do a hard refresh (Ctrl+R in Chrome) to see if that helps. The East Coast location you're seeing is the default setting that was there before (Woods Hole) and is still used as a fallback if no other location is provided

**Comment by jonatanmindroad** [comment]
Lo and behold. Waiting over the weekend solved it.
