### ISSUE TITLE
Increase mousewheel zooming speed on timeline (if possible)

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#42]
try to workaround plotly's glacial default speed

**Comment by joefutrelle** [comment]
https://stackoverflow.com/questions/7408100/can-i-change-the-scroll-speed-using-css-or-jquery

**Comment by mike-kaimika** [comment]
Still working on this one, but there appear to be road blocks to each option we find

It doesn't look like plotly exposes a way to trigger the zoom function manually, nor does it expose those buttons in the modebar (what they call it); I believe what I read was coming from the developers on that

The fix you listed above might work, but it appears as though its overriding the default scroll even for the page and doing something custom. That approach would mean us needing to trigger the zoom even for the timeline, which brings us back to the first problem

Another possible option is to capture the amount that was zoomed, and modify it:
https://codepen.io/etpinard/pen/bWoJPr

Or just making our own zoom, by taking the current x axis range and increasing/decreasing it by some specific amount based on the resolution

Both of those options would require some additional logic though, and not just affecting the zoom level by a scale factor

**Comment by joefutrelle** [comment]
This appears to be a browser-specific issue. In Chrome and Edge, the scroll wheel speed is fine, but in Firefox it's too slow.

**Comment by joefutrelle** [comment]
This looks impossible to fix.
