### ISSUE TITLE
Are the dates/times shown on the timeline x axis in UTC?

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#5]
They should be

**Comment by mike-kaimika** [comment]
@joefutrelle They should be in UTC already? We don't do any adjustments on the dates which are basically just passed through to the timeline from the API. If you hit the API directly:
http://localhost:8000/api/test1/time-series/size?resolution=hour

The times come back with no offset which I believe means they are in UTC:
`{"x": ["2017-05-09T00:00:00Z", "2017-05-09T01:00:00Z", "2017-05-09T02:00:00Z",`

**Comment by joefutrelle** [comment]
Yeah, all the times everywhere in the backend are in UTC. If I see an issue on the frontend I'll open an issue, otherwise I'm closing this. I remember having this issue with the Javascript library I used on the old site to display times/dates.
