### ISSUE TITLE
back button doesn't work when navigating between bins on the dataset page

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#74]
To reproduce:

1. Select a bin on the timeline
1. A new `?bin_id=` URL will appear in the address bar
1. Now click back

Behavior

The `bin_id` parameter will change in the address bar, but it won't reselect the previous bin

**Comment by mike-kaimika** [comment]
FYI, I have a way to fix this, so an update is forthcoming
