### ISSUE TITLE
fewer clicks to compare images

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#75]
On the old site the image display on the dataset page is not a modal, meaning that if you click on an image and then want to see another one, all you have to do is click on the mosaic again. In a1 you have to dismiss the modal before you can click on another one to compare, and this slows down the workflow.

This probably requires dropping the modal in favor of something like a card that pops up above the mosaic and that's full-width so that it can show the image at full resolution (see #72) if possible.

A typical use case for this workflow is evaluating how in focus the images are.

**Comment by joefutrelle** [comment]
This affects #67

**Comment by mike-kaimika** [comment]
Related to #104

**Comment by mike-kaimika** [comment]
Now that we aren't loading images in a modal (due to the combined page), is anything further needed on this one?
