### ISSUE TITLE
"latest bin" selected by default changes upon timeline pan/zoom

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#84]
This was exposed by the progressive timeline loading feature.

The selected bin should default initially and then stay that way even if the user changes the range of the timeline.

**Comment by mike-kaimika** [comment]
@joefutrelle Are you still seeing this issue? I just tried it, and the select bin appears to stay where it is through zooming and panning

**Comment by joefutrelle** [comment]
I'm still seeing this, but I didn't give steps to reproduce it. Here they are:

1. Navigate to a time series. The rightmost bar in the metrics plot will be red and the latest bin will be selected.
1. Pan left so the latest bin is off screen. The rightmost bar now visible will be red. The bin selection will not change, but the red bar is still shown in the wrong place.
1. Now pan back so the latest bin is visible. Its bar will be red as it should be.

**Comment by mike-kaimika** [comment]
Pushed a fix for this one
