### ISSUE TITLE
display lat/lon rounded to 4 decimal places

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#87]
floating point arithmetic sometimes results in lat/lons with unreasonable amounts of precision. Lat/lons should just be rounded to 4 decimal places.

Maybe 5, but once this is implemented we can always change it.

**Comment by joefutrelle** [comment]
![image](https://user-images.githubusercontent.com/2365298/58903102-90141480-86d2-11e9-9485-16225da53583.png)

**Comment by mike-kaimika** [comment]
Completed; set to 4 for now, but can be changed with a constant at the top of the site.js file
