### ISSUE TITLE
plotting: like axes should have the same scale

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#91]
when x is plotted against y (or height against width) they should have the same scale, so that neither axis is stretched or squished relative to the other. obviously this is only for the situation where you have the same unit on both axes, and may be limited to x/y/height/width.

**Comment by mike-kaimika** [comment]
I haven't been able to get anything consistent going, but so far, it looks like one of the following is what we need to use to enforce the scale:

https://plot.ly/javascript/reference/#layout-xaxis-scaleanchor
https://plot.ly/javascript/reference/#layout-scene-aspectratio

**Comment by mike-kaimika** [comment]
@joefutrelle I pushed an update the other day for this one (specifically the x/y and width/height combinations). Let me know if anything more  is needed
