### ISSUE TITLE
outliers make temperature / humidity plots useless

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#96]
When there are outliers in temperature and humidity data, the y axis is scaled to show them, and then the good data is impossible to read.

The best solution is to somehow scale the timeline based on the metric data with outliers excluded.

A workaround that may be sufficient for a2 is to constrain the values to a reasonable range. This has the disadvantage that those adjusted values would not be easily distinguishable from good data.

**Comment by joefutrelle** [comment]
humidity can be constrained to 0-100. I see some bins with ~900% humidity which is obviously bogus.
temperature can also be constrained, but it's less clear what the range should be. IFCBs are warm on the inside, so there's definitely a practical lower bound to temperature, but the upper bound is less clear. maybe it should be the boiling point of seawater ...

**Comment by mike-kaimika** [comment]
Pushed a temporary workaround of this as part of the generate_time_series endpoint URL. Leaving open since that's not really a final a solution (I don't think)

**Comment by joefutrelle** [comment]
the final solution is to constrain the y axis scale so that the values are unmodified but the user would have to change the y axis scale to see them.
